language: python

cache:
  - pip
  - apt

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run -m unittest
  - coverage report -m

after_success:
  - export TBS_CLI_VERSION=0.0.10
  - bash travis/post_success.sh

notifications:
  slack: 3blades:MSaGYZPPXj44OWqhhpO2ycWm
