language: python

cache:
  - pip
  - apt

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run -m unittest
  - coverage report -m

after_success:
  - bash travis/post_success.sh

notifications:
  slack: 3blades:MSaGYZPPXj44OWqhhpO2ycWm

env:
  - TBS_CLI_VERSION=0.0.7
  - TWINE_REPOSITORY=https://pypi.python.org/pypi